// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrMMkdm6w1iTY4Xh0J56SFWTyZeK49bzU',
    appId: '1:200698208242:web:5e63f4b757a002432c156b',
    messagingSenderId: '200698208242',
    projectId: 'finance-372ed',
    authDomain: 'finance-372ed.firebaseapp.com',
    databaseURL: 'https://finance-372ed-default-rtdb.firebaseio.com',
    storageBucket: 'finance-372ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhp1UMa1QYxJZ9HQQrhxOFOE05lqy4uI4',
    appId: '1:200698208242:android:86437c3013bd8bb32c156b',
    messagingSenderId: '200698208242',
    projectId: 'finance-372ed',
    databaseURL: 'https://finance-372ed-default-rtdb.firebaseio.com',
    storageBucket: 'finance-372ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACxyrU8vTmhCaENh1P7gsL-Vs5GR07Q8Q',
    appId: '1:200698208242:ios:57cc6d8f6729e8b42c156b',
    messagingSenderId: '200698208242',
    projectId: 'finance-372ed',
    databaseURL: 'https://finance-372ed-default-rtdb.firebaseio.com',
    storageBucket: 'finance-372ed.appspot.com',
    iosBundleId: 'com.example.flutterMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACxyrU8vTmhCaENh1P7gsL-Vs5GR07Q8Q',
    appId: '1:200698208242:ios:cf0210597b97a04d2c156b',
    messagingSenderId: '200698208242',
    projectId: 'finance-372ed',
    databaseURL: 'https://finance-372ed-default-rtdb.firebaseio.com',
    storageBucket: 'finance-372ed.appspot.com',
    iosBundleId: 'com.example.flutterMarket.RunnerTests',
  );
}
