// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu8GS_YxgCRGY4h2A8pkvR_WHmK6A-61s',
    appId: '1:63456349150:web:2e55dc3061d5892d136b4f',
    messagingSenderId: '63456349150',
    projectId: 'market-d068c',
    authDomain: 'market-d068c.firebaseapp.com',
    storageBucket: 'market-d068c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAPF6tjbl0NKFWJQN3KqXA5UKGUZAA4Ec',
    appId: '1:63456349150:android:9fce695aa94b6fb6136b4f',
    messagingSenderId: '63456349150',
    projectId: 'market-d068c',
    storageBucket: 'market-d068c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACTgbfypeLGJhf6F6R3rjeS2xZ5bhy0xY',
    appId: '1:63456349150:ios:48847761ac42b7b4136b4f',
    messagingSenderId: '63456349150',
    projectId: 'market-d068c',
    storageBucket: 'market-d068c.appspot.com',
    iosBundleId: 'com.example.flutterMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACTgbfypeLGJhf6F6R3rjeS2xZ5bhy0xY',
    appId: '1:63456349150:ios:8dd554d36dfa9abb136b4f',
    messagingSenderId: '63456349150',
    projectId: 'market-d068c',
    storageBucket: 'market-d068c.appspot.com',
    iosBundleId: 'com.example.flutterMarket.RunnerTests',
  );
}
